### ISSUE TITLE
swift 2.0 support ?

### ISSUE THREAD

**Issue by liufsd** [Yalantis/PullToMakeFlight#1]

**Comment by maksym-letiushov** [comment]
Hi. Currently we don't have time to update code to swift 2.0, but maybe we will update it closer to the Xcode 7 release date.

**Comment by liufsd** [comment]
yeah,swift 2.0 change, i test it on Xcode 7 beta. but run fail.

**Comment by maksym-letiushov** [comment]
If you want to test it run it on XCode 6 that uses swift 1.2

**Comment by liufsd** [comment]
oh.i known that. but i want to use it for my new project on Xcode 7.

**Comment by Art3mS1d** [comment]
Hello, @79144876 
Swift 2.0 now supported.
We created a branch to maintain it
https://github.com/Yalantis/PullToMakeFlight/tree/swift_2.0

**Comment by liufsd** [comment]
Good.
Thanks.
