### ISSUE TITLE
Framework not found Pods

### ISSUE THREAD

**Issue by NisalChathuranga** [Yalantis/PullToMakeFlight#7]
![screen shot 2016-05-22 at 7 03 52 am](https://cloud.githubusercontent.com/assets/17734914/15451632/677fe5e0-1feb-11e6-91aa-a4ed5e733b39.png)
According to Xcode new update, it didn't work for me. How do i solve this?

**Comment by serejahh** [comment]
Hi @NisalChathuranga! Thank you for reporting the issue. Please, check out the repo with update
