### ISSUE TITLE
Grouped style

### ISSUE THREAD

**Issue by diogo10** [Yalantis/PullToMakeFlight#8]
Hi guys, when I change to Plan styles...works like a charm. do you know what's could I change to archive it?

![simulator screen shot 6 jun 2016 09 04 26](https://cloud.githubusercontent.com/assets/1541244/15815578/e6100864-2bc5-11e6-8e8b-2a37372a5951.png)

**Comment by serejahh** [comment]
Hi @diogo10. Thanks for reporting the issue. It happens because `FlightView` has `clipsToBounds = false`. I'll fix the issue
